### ISSUE TITLE
PHP 7 - mPDF is not working

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/fancy_treeview#43]
Since upgrading to PHP 7 I get a error message when clicking the pdf-icon in fance treeview.
I already posted it in the webtrees forum: 
https://www.webtrees.net/index.php/en/forum/4-customising/31006-fancy-treeview-mpdf-has-a-deprecated-constructor#57479

Fisharebest replied with this two links - maybe usefull, but I can not fix it:

github.com/mpdf/mpdf/issues/68
github.com/mpdf/mpdf/commit/61b0048530f1...a548465e41a597d2908e

Here is the error message:

#0 /modules_v3/fancy_treeview/src/Template/PdfTemplate.php:37 ErrorException("Methods with the same name as their class will not be constructors in a future version of PHP; mPDF has a deprecated constructor")
#1 /modules_v3/fancy_treeview/src/Template/PdfTemplate.php:37 require_once()
#2 /modules_v3/fancy_treeview/module.php:292 pageBody()
#3 /module.php:26 modAction()

**Comment by JustCarmen** [comment]
As Greg mentioned this issue is fixed in the development branch of [mPDF](https://github.com/mpdf/mpdf).

Inside my modules I don't use development versions of third party code, only stable releases.
But as far as I can see the development branch of mPDF until the current commit is reliable enough to use, although I won't recommend to use it in a production environment. I've tested it upon the latest Fancy Treeview PDF release.

Maybe you have noticed it already, but I have split up the PDF option from the Fancy Treeview module  into its own module: [Fancy Treeview PDF](https://github.com/JustCarmen/fancy_treeview_pdf). 

To use the latest development version of mPDF inside the Fancy Treeview PDF module act as follows:
* Download the latest version of the [Fancy Treeview module](https://github.com/JustCarmen/fancy_treeview/releases/latest);
* Download the latest version of the [Fancy Treeview PDF module](https://github.com/JustCarmen/fancy_treeview_pdf/releases/latest);
* Download the [development version of mPDF](https://github.com/mpdf/mpdf). Click on the 'Download Zip' button inside the repository.
* Unpack the mpdf-development.zip and rename the folder 'mpdf-development' to 'mpdf'.
* Replace the mpdf folder inside the Fancy Treeview PDF module with the development version of mpdf.
* Open the file src/template/PdfTemplate and change line 35 into this:

   ```require_once(WT_MODULES_DIR . $this->getName() . '/mpdf/mpdf.php');``` 

    In stead of changing the line yourself, you could also grab [the latest development version](https://github.com/JustCarmen/fancy_treeview_pdf/blob/master/src/Template/PdfTemplate.php) of this file, where I have removed the version number of the mpdf folder for future releases.

**Comment by HonkXL** [comment]
Hi Carmen,
great - I just uploaded everything as in your workaround and it works now. Thank you!

**Comment by HonkXL** [comment]
One small issue with this: the downloaded pdf-file has no file ending .pdf
My Mac still opens them, but I think this would be a problem on Windows.

**Comment by JustCarmen** [comment]
This should be fixed now.
